# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Autosea Thesis Proposals
description: > # this means to ignore newlines until "baseurl:"
    A description of the current project and master theses for the Autosea project. The overall project topic is maritime target tracking and collision avoidance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://autosea.github.io" # the base hostname & protocol for your site
github_username:  autosea

# Build settings
markdown: kramdown
